# Generated by Django 4.2.7 on 2025-10-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='feedback_app.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers_branch', to='feedback_app.branch'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers_sem', to='feedback_app.semester'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='feedback_app.year'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
