# Generated by Django 4.2.7 on 2025-10-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_student_class_teacher_teacher_assigned_class_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division name (A, B, C, etc.)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='feedback_app.division'),
        ),
        migrations.AddField(
            model_name='subject',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='feedback_app.division'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='feedback_app.division'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('code', 'semester', 'branch', 'division')},
        ),
    ]
