# Generated by Django 4.2.7 on 2025-11-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_department_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='feedbacksummary',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'ordering': ['-assigned_date'], 'verbose_name': 'Teacher Subject Assignment', 'verbose_name_plural': 'Teacher Subject Assignments'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='feedbacksummary',
            old_name='negative_count',
            new_name='negative_comments_count',
        ),
        migrations.RenameField(
            model_name='feedbacksummary',
            old_name='neutral_count',
            new_name='neutral_comments_count',
        ),
        migrations.RenameField(
            model_name='feedbacksummary',
            old_name='positive_count',
            new_name='positive_comments_count',
        ),
        migrations.RenameField(
            model_name='feedbacksummary',
            old_name='total_feedback_count',
            new_name='total_responses',
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'year')},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password_reset_token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prn_number',
            field=models.CharField(blank=True, help_text='Student PRN or Employee ID', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(help_text='Division name (A, B, C, etc.)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='assignment_feedback',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='No comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_content',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='interaction_quality',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_satisfaction',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.semester'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='feedback_app.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='feedback_app.subject'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, default='No comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='feedback_app.teacher'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teaching_effectiveness',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.semester'),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_summaries', to='feedback_app.subject'),
        ),
        migrations.AlterField(
            model_name='feedbacksummary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_summaries', to='feedback_app.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='feedback_app.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='feedback_app.division'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_app.year'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='feedback_app.division'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers_branch', to='feedback_app.branch'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers_div', to='feedback_app.division'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers_sem', to='feedback_app.semester'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_app.branch'),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
