# Generated by Django 4.2.7 on 2025-11-01 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_alter_division_options_alter_feedbacksummary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='assignment_feedback',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='No comments', help_text='Additional comments'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course_content',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='interaction_quality',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_satisfaction',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True, default='No suggestions', help_text='Suggestions for improvement'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teaching_effectiveness',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Optional: Specific division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='feedback_app.division'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assigned_class_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='feedback_app.division'),
        ),
    ]
